# SITE CONFIGURATION
title: some stuff i've done # your site title
author: Seth So # You :P
description: A compilation of some stuff I've done.

#if custom domain:
baseurl: # the subpath of your site, e.g. /blog
url: "https://sethso.com" # the base hostname & protocol for your site, e.g. http://example.com

#if not custom domain:
#baseurl: "/portfolio" # the subpath of your site, e.g. /blog
#url: "https://seth-so.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Seth So
  links:
    - https://twitter.com/sethso97
    - https://www.facebook.com/sethso
    - https://www.linkedin.com/in/seth-so
    - https://plus.google.com/+sethso97
    - https://github.com/seth-so

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Hello Nate and Mr. Carnovale

hero_img: posts/heroshot-main_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: sethso97@gmail.com # email for form submission

linkedin_username: in/seth-so
# twitter_username:
github_username:  seth-so # replace with your_github_username or comment to remove link from footer
# instagram_username:

disqus:
  shortname: sethso # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
